configs:
  caddyfile_v11:
    file: ./Caddyfile
  prometheus_config_v4:
    file: ./prometheus.yml

services:
  caddy:
    image: caddy:2
    ports:
      - "8081:80"
    networks:
      - backend
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    configs:
      - source: caddyfile_v11
        target: /etc/caddy/Caddyfile
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == 24c257bb3f84

  api:
    image: pezinho/spotshare-api:latest
    networks:
      - backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=spotshare
      - DB_USER=spotshare
      - DB_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == worker-api

  db:
    image: mysql:8
    command:
      - "--log-bin-trust-function-creators=1"
      - "--event_scheduler=ON"
    networks:
      - backend
    environment:
      MYSQL_DATABASE: spotshare
      MYSQL_USER: spotshare
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker-db

  prometheus:
    image: prom/prometheus:latest
    networks:
      - backend
    configs:
      - source: prometheus_config_v4
        target: /etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - prometheus_data:/prometheus
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker-monitoring

  grafana:
    image: grafana/grafana:latest
    networks:
      - backend
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=grafana.spotshareapi.fr
      - GF_SERVER_ROOT_URL=https://grafana.spotshareapi.fr
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker-monitoring

  node_exporter:
    image: prom/node-exporter:latest
    networks:
      - backend
    deploy:
      mode: global
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - backend
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro


networks:
  backend:
    external: true

volumes:
  db_data:
  caddy_data:
  caddy_config:
  prometheus_data:
  grafana_data:

secrets:
  mysql_password:
    external: true

