INSERT INTO countries (country_code, creation_date, last_modification_date) VALUES 
('FRA', NOW(), NOW()), 
('USA', NOW(), NOW()), 
('ESP', NOW(), NOW()), 
('ITA', NOW(), NOW()), 
('DEU', NOW(), NOW()), 
('GBR', NOW(), NOW()), 
('JPN', NOW(), NOW()), 
('CHN', NOW(), NOW()), 
('BRA', NOW(), NOW()), 
('CAN', NOW(), NOW()), 
('AUS', NOW(), NOW()), 
('MEX', NOW(), NOW()), 
('ARG', NOW(), NOW()), 
('IND', NOW(), NOW()), 
('RUS', NOW(), NOW()), 
('ZAF', NOW(), NOW()),
('EGY', NOW(), NOW()), 
('MAR', NOW(), NOW()), 
('KEN', NOW(), NOW()), 
('NGA', NOW(), NOW()), 
('THA', NOW(), NOW()), 
('VNM', NOW(), NOW()), 
('KOR', NOW(), NOW()), 
('IDN', NOW(), NOW()),
('TUR', NOW(), NOW()), 
('SAU', NOW(), NOW()), 
('ARE', NOW(), NOW()), 
('GRC', NOW(), NOW()), 
('PRT', NOW(), NOW()), 
('NLD', NOW(), NOW()), 
('BEL', NOW(), NOW()), 
('CHE', NOW(), NOW()),
('AUT', NOW(), NOW()), 
('SWE', NOW(), NOW()), 
('NOR', NOW(), NOW()), 
('DNK', NOW(), NOW()), 
('FIN', NOW(), NOW()), 
('POL', NOW(), NOW()), 
('CZE', NOW(), NOW()), 
('HUN', NOW(), NOW());


INSERT INTO country_tl (country_id, language_code, country_name) VALUES
(1, 'FR', 'France'), (2, 'FR', 'États-Unis'), (3, 'FR', 'Espagne'),
(4, 'FR', 'Italie'), (5, 'FR', 'Allemagne'), (6, 'FR', 'Royaume-Uni'),
(7, 'FR', 'Japon'), (8, 'FR', 'Chine'), (9, 'FR', 'Brésil'),
(10, 'FR', 'Canada'), (11, 'FR', 'Australie'), (12, 'FR', 'Mexique'),
(13, 'FR', 'Argentine'), (14, 'FR', 'Inde'), (15, 'FR', 'Russie'),
(16, 'FR', 'Afrique du Sud'), (17, 'FR', 'Égypte'), (18, 'FR', 'Maroc'),
(19, 'FR', 'Kenya'), (20, 'FR', 'Nigeria'), (21, 'FR', 'Thaïlande'),
(22, 'FR', 'Vietnam'), (23, 'FR', 'Corée du Sud'), (24, 'FR', 'Indonésie'),
(25, 'FR', 'Turquie'), (26, 'FR', 'Arabie Saoudite'), (27, 'FR', 'Émirats Arabes Unis'),
(28, 'FR', 'Grèce'), (29, 'FR', 'Portugal'), (30, 'FR', 'Pays-Bas'),
(31, 'FR', 'Belgique'), (32, 'FR', 'Suisse'), (33, 'FR', 'Autriche'),
(34, 'FR', 'Suède'), (35, 'FR', 'Norvège'), (36, 'FR', 'Danemark'),
(37, 'FR', 'Finlande'), (38, 'FR', 'Pologne'), (39, 'FR', 'République Tchèque'),
(40, 'FR', 'Hongrie');

INSERT INTO country_tl (country_id, language_code, country_name) VALUES
(1, 'EN', 'France'), (2, 'EN', 'United States'), (3, 'EN', 'Spain'),
(4, 'EN', 'Italy'), (5, 'EN', 'Germany'), (6, 'EN', 'United Kingdom'),
(7, 'EN', 'Japan'), (8, 'EN', 'China'), (9, 'EN', 'Brazil'),
(10, 'EN', 'Canada'), (11, 'EN', 'Australia'), (12, 'EN', 'Mexico'),
(13, 'EN', 'Argentina'), (14, 'EN', 'India'), (15, 'EN', 'Russia'),
(16, 'EN', 'South Africa'), (17, 'EN', 'Egypt'), (18, 'EN', 'Morocco'),
(19, 'EN', 'Kenya'), (20, 'EN', 'Nigeria'), (21, 'EN', 'Thailand'),
(22, 'EN', 'Vietnam'), (23, 'EN', 'South Korea'), (24, 'EN', 'Indonesia'),
(25, 'EN', 'Turkey'), (26, 'EN', 'Saudi Arabia'), (27, 'EN', 'United Arab Emirates'),
(28, 'EN', 'Greece'), (29, 'EN', 'Portugal'), (30, 'EN', 'Netherlands'),
(31, 'EN', 'Belgium'), (32, 'EN', 'Switzerland'), (33, 'EN', 'Austria'),
(34, 'EN', 'Sweden'), (35, 'EN', 'Norway'), (36, 'EN', 'Denmark'),
(37, 'EN', 'Finland'), (38, 'EN', 'Poland'), (39, 'EN', 'Czech Republic'),
(40, 'EN', 'Hungary');
